### PR TITLE
Added recursive search of functions rather than linear search 

### PR DESCRIPTION
**Pull request by rohanailoni**

### CODE REVIEW

**Comment by rohanailoni** [comment]
I think recursive function is good and also the *args is in sorted order so i changed it into **kwargs

**Comment by sansyrox** [comment]
@rohanailoni , correct me if am wrong but does this PR add a recursive implementation and performs a deep search on the specified function?

**Comment by rohanailoni** [comment]
> @rohanailoni , correct me if am wrong but does this PR add a recursive implementation and performs a deep search on the specified function?

yeah it recursively(dfs) search until it get the `fun_name==inner_name` so it return only function but I havent though about if there are multiple function it will just return the first found

### Is return a function(if not found `None`) preferable or a list is preferable?

**Comment by sansyrox** [comment]
@rohanailoni , apologies for the late review. I am having some busy days. :(

Initially, I only meant this to be a top level search. But now if we want to consider a recursive search, how do you plan to handle an instance where there is a top level and a nested function of the same name? 

Also, let's change the name from `nestd` to `get_nested_function` as `nestd/nested` don't really do enough justice to explain the purpose of the function.

**Comment by rohanailoni** [comment]
I have seen this message long age :sweat_smile: but couldn't answer there are lot of interviews are going on 
I also though about return instance I have written code for both but only commited one

This return only top nested function
```python
def nestd(fx,inner_name,**free_vars):
    """Find the code object of an inner function recursively and  return it as a callable object.

    Arguments:
        fx (function or method): A function object with an inner function.
        inner_name (str): The name of the inner function we want access to
        **free_vars (dict(str: any)): A dictionary with values for the free
            variables in the context of the inner function.
    Returns:
        A function object for the inner function, with context variables set or None if none of the function matches with inner_name.
    """
    if not isinstance(fx,(types.FunctionType,types.MethodType)):
        raise Exception("Supplied param is not a function or a method type")
    fx=fx.__code__
    for const in fx.co_consts:
        if isinstance(const,types.CodeType):
            if const.co_name==inner_name:
                return types.FunctionType(const,globals(),None,None,tuple(free_var(free_vars[name]) for name in const.co_freevars))
            else:
                fun=nestd(types.FunctionType(const,globals(),None,None,tuple(free_var(free_vars[name]) for name in const.co_freevars)),inner_name,**free_vars)
                """"This recusrive function may return None that means There is no funciton with matching name in the given depth so insted of stoping it goes for another depth."""
                """But if it returns some function then the match is found"""
                if(fun!=None):
                    return fun
    return None
```

This one return a list of all the functions in top down(recusive depth search is used) so first function to be mached with `inner_name` will be on top of list(lower index)

```python
def nestd(fx,inner_name,**free_vars):
    """Find the code object of an inner function recursively and  return it as a callable object.

    Arguments:
        fx (function or method): A function object with an inner function.
        inner_name (str): The name of the inner function we want access to
        **free_vars (dict(str: any)): A dictionary with values for the free
            variables in the context of the inner function.
    Returns:
        A function object for the inner function, with context variables set or None if none of the function matches with inner_name.
    """
    if not isinstance(fx,(types.FunctionType,types.MethodType)):
        raise Exception("Supplied param is not a function or a method type")
    fx=fx.__code__
    cache=[]
    for const in fx.co_consts:
        if isinstance(const,types.CodeType):
            temp=types.FunctionType(const,globals(),None,None,tuple(free_var(free_vars[name]) for name in const.co_freevars))
            if const.co_name==inner_name:
                cache.append(temp)
            fun=nestd(temp,inner_name,**free_vars)
            cache+=fun
    return cache
```


And I am not sure which one of the both method is much benificial as i haven't worked much on nested function

Also though of any datastrcture to be return in place of list(`in the second code`) but couldnt get any better idea



In the present library there are 3 functions
* nested
* get_all_nested
* get_all_deep_nested

Ig `get_all_nested` is of no use as `get_all_deep_nested` can also work like the preceding function

> Also, let's change the name from `nestd` to `get_nested_function` as `nestd/nested` don't really do enough justice to explain the purpose of the function.

I agree with that

**Comment by sansyrox** [comment]
@rohanailoni , no worries :D

> This one return a list of all the functions in top down(recusive depth search is used) so first function to be mached with inner_name will be on top of list(lower index)

If we are just returning the top function, then I don't see a reason to implement a recursive search. As we have get `get_all_deep_nested`.

> Ig get_all_nested is of no use as get_all_deep_nested can also work like the preceding function

`get_all_nested` is the function that returns top level functions and `get_all_deep_nested` returns the entire tree. No?

**Comment by rohanailoni** [comment]
> `get_all_nested` is the function that returns top level functions and `get_all_deep_nested` returns the entire tree. No?

Yeah It returns a dict And i got your point from days i was in a dilemma on why to get `only top level` now i got it .It is like a use-case for a user to only toplevel functions

**Comment by sansyrox** [comment]
@rohanailoni , perfect then :D

**Comment by rohanailoni** [comment]
I will be closing the Pull request Then :)

**Pull request closed without merging**
